### ISSUE TITLE
Set domain command

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#7]
We need to get the syntax for this (and the httpopen command #6) right
Basically the command is supposed to change the value in {{appdir}/.env and restart the traefik proxy (to get it to take effect
TODO: Review the SSL state in the end of this command....

**Comment by niryariv** [comment]
@liorkesos are we setting URL or just domain here?

**Comment by niryariv** [comment]
Per discussion w/ @liorkesos changing this to set *domain* instead of URL - we'll be asking the user for the domain only

**Comment by billylkc** [comment]
Implemented in dev, should be available in 0.1.6

**Comment by niryariv** [comment]
@niryariv review

**Comment by niryariv** [comment]
@liorkesos need your advice on how to test

**Comment by billylkc** [comment]
I just watched the loom video on the SetDomain command, basically it is an app command, need a list to specify which one is app command, and which one are general available (supported by all apps). Coz I just checked the command mapping list, gitbucket is not supported for the particular command.

@niryariv @liorkesos, please confirm SetDomain would be a general command

**Comment by niryariv** [comment]
@billylkc can u link to the command mapping list you refer to?

**Comment by billylkc** [comment]
For the latest command mapping list, please refer to the first few lines under the **./hossted/commands.go** file

**Comment by billylkc** [comment]
And for the record, we had the app-specific/general available commands mapping list, because of the following reasons from our previous discussion, please help to review if the reasons are still valid.
- Even for the same command, say set random_cmd, different apps could have different logics in the docker-compose (e.g. different lines to comment, etc,..)
- Some command is only available to a specific set of app (say wordpress only)

**Comment by niryariv** [comment]
As discussed - make this generally available

**Comment by niryariv** [comment]
@liorkesos need guidance on how to test this
